unique_ids:
  forms:
    Usuarios.EditGroups: QYWXE2JEQMF2D2HB5RALXMZ6V33ZMC7I
    DashBoard_V2.EditarGrupos.ListaGrupos: 6XLSC6UEGVOMNDJLWQJIOYPY64F7P3Q5
    Usuarios.CreateUser: A65IGXZDR5DSCOFWAVZGQY6FD5SOQWII
    Usuarios.UserTemplate: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
    Login: USBYLWDVV3EOLILIJAMPBY3DL5MTA2SX
    EditarSensor: RYRIK6ZJBBDRPDCBAY7NWPDIGI75SW3F
    Usuarios: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    DashBoard_V2: JXU6QQVYVPBJFNCCQOJ4CDYV5IEN36BV
    Sensores: WH3DTIPQ5TOINBE7DT27RWUS5RUV5YW3
    DashBoard_V2.EditarGrupos: QTWWYQLDS5LLTW2NGPTQIT44UAQCPZ2Y
    Usuarios.EditGroups.GroupTemplate: TUPMA4PYU4Q53AFCJMUHDNTIJMX2HURT
    DashBoard_V2.ItemTemplate1: O6RDPWEWU44GOOMLGYWTHXXEVSEMNVQK
    Sensores.SensorTemplate: Y3XBBFSJLQL656A3D6DTO3N3X7RNNGTP
    Sensores.EditarSensor: VLJHZCY3SJWRQMW6XWDF74RAO633QPWB
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
  modules:
    functions: TMINS64CGVKJWRGQRWB2UP7YK5OYPQRA
    routes: LTWIRSS4WZ3VOBXGCMJ5MOS7WYBH5LTZ
  server_modules: {}
  assets:
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
