unique_ids:
  forms:
    Login: USBYLWDVV3EOLILIJAMPBY3DL5MTA2SX
    EditarSensor: RYRIK6ZJBBDRPDCBAY7NWPDIGI75SW3F
    Usuarios: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    DashBoard_V2: JXU6QQVYVPBJFNCCQOJ4CDYV5IEN36BV
    Sensores.Sensor: NSRJNCKBCSL46AJNQB4U5OSXEAWF3CQS
    Sensores: L7RYLFC2WG4YGM7N4OUAPNWZJEOQ5GZ7
    Usuarios.TemplateRow: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
    DashBoard_V2.ItemTemplate1: O6RDPWEWU44GOOMLGYWTHXXEVSEMNVQK
    Login.RowTemplate1: 2GMHQ4KSAK7MOP2YT6HZLAODVWGGTLLX
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
  modules:
    routes: LTWIRSS4WZ3VOBXGCMJ5MOS7WYBH5LTZ
    functions: TPISDBUJ2XFQWS5I35UHTVPVIEEZC2ML
  server_modules: {}
  assets:
    roboto.css: ICADM5CGPCVKT22CA4PJLYOZJH3OBT2W
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
