unique_ids:
  forms:
    Admin: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
    Admin.TemplateRow: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
  modules: {}
  server_modules:
    ServerModule1: DQ3O3EX2G3XGTPH6IUSZXOVNZD2EZQV7
  assets:
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
