unique_ids:
  forms:
    Admin: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    Admin.TemplateRow: LDK7EJ77MEW5F2BQWXIIBHOG6FNNB7A7
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
  modules: {}
  server_modules:
    ServerModule1: DQ3O3EX2G3XGTPH6IUSZXOVNZD2EZQV7
  assets:
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
