unique_ids:
  forms:
    Admin: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    Admin.TemplateRow: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    EditarSensor: BPWB3VDHGUONJXKHQHMHBMD6PRY6XSGR
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
    Sensores: QTHCA5DY5KEGZSJH3QXHV7XMAG36ZAWB
    Sensores.Sensor: RQY34KLTTV6P2SVMQDET4IIT7NYAX6M2
  modules:
    routes: LTWIRSS4WZ3VOBXGCMJ5MOS7WYBH5LTZ
  server_modules: {}
  assets:
    roboto.css: ICADM5CGPCVKT22CA4PJLYOZJH3OBT2W
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
