unique_ids:
  forms:
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    DashBoard_V2: JXU6QQVYVPBJFNCCQOJ4CDYV5IEN36BV
    EditarSensor: RYRIK6ZJBBDRPDCBAY7NWPDIGI75SW3F
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
    Sensores: L7RYLFC2WG4YGM7N4OUAPNWZJEOQ5GZ7
    Sensores.Sensor: NSRJNCKBCSL46AJNQB4U5OSXEAWF3CQS
    Usuarios: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    Usuarios.TemplateRow: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
  modules:
    routes: LTWIRSS4WZ3VOBXGCMJ5MOS7WYBH5LTZ
  server_modules: {}
  assets:
    roboto.css: ICADM5CGPCVKT22CA4PJLYOZJH3OBT2W
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
