unique_ids:
  forms:
    Usuarios.EditGroups: QYWXE2JEQMF2D2HB5RALXMZ6V33ZMC7I
    DashBoard_V2.EditarGrupos.ListaGrupos: 6XLSC6UEGVOMNDJLWQJIOYPY64F7P3Q5
    Usuarios.CreateUser: A65IGXZDR5DSCOFWAVZGQY6FD5SOQWII
    Usuarios.UserTemplate: VVOYFK5KGNHLEPPKSHK2XXQV7663VXV3
    Login: USBYLWDVV3EOLILIJAMPBY3DL5MTA2SX
    EditarSensor: RYRIK6ZJBBDRPDCBAY7NWPDIGI75SW3F
    Usuarios: KYFM6KR7CZSBQN54EMAYHIAGETR2A7ZX
    DashBoard_V2: JXU6QQVYVPBJFNCCQOJ4CDYV5IEN36BV
    Sensores: E6KCOK5IZGTVCMVFVMUC6ZAJ5DYRPWNT
    DashBoard_V2.EditarGrupos: QTWWYQLDS5LLTW2NGPTQIT44UAQCPZ2Y
    Sensores.TypeTemplate: 7TJ24RY23T3OPTRTWEDYYXRBSKX4YPHB
    Usuarios.EditGroups.GroupTemplate: TUPMA4PYU4Q53AFCJMUHDNTIJMX2HURT
    DashBoard_V2.ItemTemplate1: O6RDPWEWU44GOOMLGYWTHXXEVSEMNVQK
    Sensores.SensorTemplate: T7GEIYBW2O57AYLS4AMQ4CBFYDMYTKD3
    Sensores.EditarSensor: G7SWHJH3XD4CJYCU7S6DMF6LQN7MOWPI
    DashBoard: Y3KBOBKYSGDU7KXYO3SLMRCPMDDWKC5X
    MenuLateral: MVASCYYRSIMLJJJRJXBM4BVO4VAQ2TMH
  modules:
    functions: TMINS64CGVKJWRGQRWB2UP7YK5OYPQRA
    routes: LTWIRSS4WZ3VOBXGCMJ5MOS7WYBH5LTZ
  server_modules: {}
  assets:
    standard-page.html: GYBQYUM6YU5JU6IBUF4AMO5LMUIUODFV
    theme.css: DKRRQUP4N4VIASSADC62WKC6EZPU47II
